# -*- coding: utf-8 -*-
"""inverse_mutation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jV8X4Lm7uR8XuliiVns_lCpw4XjQTrQ
"""

def inverse_mutation(individual):
    start, stop = sorted(random.sample(range(len(individual)), 2)) #taking 2 random points
    temp = individual[start:stop+1]
    temp.reverse() #inverse the temporary list
    individual[start:stop+1] = temp
    return (individual, )