# -*- coding: utf-8 -*-
"""Stochastic_Sampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jV8X4Lm7uR8XuliiVns_lCpw4XjQTrQ
"""

import random
# Example population of individuals with their fitness values
population = [
    {"id": 1, "fitness": 10},
    {"id": 2, "fitness": 5},
    {"id": 3, "fitness": 25},
    {"id": 4, "fitness": 20},
    {"id": 5, "fitness": 6}
]
total_fitness=0
for idividual in population:
     total_fitness += idividual["fitness"]

# Calculate the average fitness
average_fitness = total_fitness / len(population)
# Calculate the step size
step_size = total_fitness / len(population)
# Generate a random starting point on the wheel
start_point = random.uniform(0, step_size)
print(f'{"start point "}{start_point}')
# Initialize variables for sampling
current_position = start_point
selected_individuals = []

# Perform the sampling process
while len(selected_individuals) < len(population):

    current_position = random.uniform(0, step_size)
    print (current_position);
    for individual in population:
            if current_position <= individual["fitness"] and len(selected_individuals) < len(population):
                selected_individuals.append(individual)
                current_position += step_size

# Print the selected individuals
for individual in selected_individuals:
    print(f"Selected: Individual {individual['id']} with fitness {individual['fitness']}")