# -*- coding: utf-8 -*-
"""swap_mutation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jV8X4Lm7uR8XuliiVns_lCpw4XjQTrQ
"""
import random
def swap_mutation(individual):
    start, stop = (random.sample(range(len(individual)), 2))
    #start=random.randint(0,len(ind))
    #stop=random.randint(0,len(ind))
    temp=individual[start]
    individual[start]=individual[stop]
    individual[stop]=temp
    return (individual, )
